name: Build ZMK firmware

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: build-zmk-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
